# Generated by Django 4.0 on 2021-12-15 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SendMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameMethod', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('params', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('sendMethodID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='notification.sendmethod')),
                ('templateID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notification.template')),
            ],
        ),
    ]
